name: Deploy Angular to GitHub Pages

on:
  push:
    branches: [ main ]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        # Заставляем робота зайти в папку и установить зависимости
        run: |
          cd my-angular-app
          npm install

      - name: Build Angular
        # Заходим в папку, собираем проект
        run: |
          cd my-angular-app
          npx ng build --configuration production --base-href /my-angular-app/

      - name: Upload Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # ВАЖНО: это путь, где лежит готовый index.html
          path: my-angular-app/dist/my-angular-app/browser/

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
